import './globals.css';
import { Inter } from 'next/font/google';
import Provider from '@/context/provider';
import Header from '@/components/global/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <main style={{ margin: '50px' }}>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
